import type { Metadata } from "next";
import { Sora } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import Notification from "@/components/notification/Notification";

const sora = Sora({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={sora.className}>
        <nav className="main-navbar">
          <Notification />
          <Navbar />
        </nav>
        {children}
      </body>
    </html>
  );
}
